module.exports = [
  {
    Id: 1,
    OprationName: 'Block',
    TableName: 'Payment',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'Payment',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 2,
    OprationName: 'Not Sure',
    TableName: 'Payment',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'غير مؤكدة ',
    ControllerName: 'Payment',
    ClassName: 'info',
    RoleName: 'NULL',
    ArabicOprationDescription: 'غير مؤكدة',
    IconClass: 'el-icon-check',
    Color: 'NULL'
  },
  {
    Id: 3,
    OprationName: 'Sure',
    TableName: 'Payment',
    Status: 1,
    ReferenceStatus: 'NULL',
    OprationDescription: 'مؤكدة ',
    ControllerName: 'Payment',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'مؤكدة',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 4,
    OprationName: 'Block',
    TableName: 'InventoryItem',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'InventoryItem',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 5,
    OprationName: 'New',
    TableName: 'InventoryItem',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'InventoryItem',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 6,
    OprationName: 'Block',
    TableName: 'OrderInventory',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'OrderInventory',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 7,
    OprationName: 'New',
    TableName: 'OrderInventory',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'OrderInventory',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 8,
    OprationName: 'Block',
    TableName: 'StocktakingInventory',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'StocktakingInventory',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'مرصد',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 9,
    OprationName: 'New',
    TableName: 'StocktakingInventory',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'StocktakingInventory',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'غير مرصد',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 10,
    OprationName: 'Block',
    TableName: 'UnitItem',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'UnitItem',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 11,
    OprationName: 'New',
    TableName: 'UnitItem',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'UnitItem',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 12,
    OprationName: 'Block',
    TableName: 'MenuItem',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'MenuItem',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 13,
    OprationName: 'New',
    TableName: 'MenuItem',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'MenuItem',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 14,
    OprationName: 'Block',
    TableName: 'OriginItem',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'OriginItem',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 15,
    OprationName: 'New',
    TableName: 'OriginItem',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'OriginItem',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 16,
    OprationName: 'Block',
    TableName: 'Item',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'Item',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 17,
    OprationName: 'New',
    TableName: 'Item',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'Item',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 18,
    OprationName: 'Block',
    TableName: 'Vendor',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'Vendor',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 19,
    OprationName: 'New',
    TableName: 'Vendor',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'Vendor',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 20,
    OprationName: 'Block',
    TableName: 'InventoryMovement',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'InventoryMovement',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 21,
    OprationName: 'New',
    TableName: 'InventoryMovement',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'InventoryMovement',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 22,
    OprationName: 'Block',
    TableName: 'StockMovement',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'StockMovement',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 23,
    OprationName: 'New',
    TableName: 'StockMovement',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'StockMovement',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 24,
    OprationName: 'Block',
    TableName: 'SalesInvoice',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'SalesInvoice',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 25,
    OprationName: 'Not Sure',
    TableName: 'SalesInvoice',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'غير مؤكدة ',
    ControllerName: 'SalesInvoice',
    ClassName: 'info',
    RoleName: 'NULL',
    ArabicOprationDescription: 'غير مؤكدة',
    IconClass: 'el-icon-check',
    Color: 'NULL'
  },
  {
    Id: 26,
    OprationName: 'Sure',
    TableName: 'SalesInvoice',
    Status: 1,
    ReferenceStatus: 0,
    OprationDescription: 'تم تحصيلها',
    ControllerName: 'SalesInvoice',
    ClassName: 'SalesInvoice',
    RoleName: 'NULL',
    ArabicOprationDescription: 'تم تحصيلها',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 27,
    OprationName: 'Block',
    TableName: 'PurchaseInvoice',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'PurchaseInvoice',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 28,
    OprationName: 'New',
    TableName: 'PurchaseInvoice',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'PurchaseInvoice',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'مؤكدة',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 29,
    OprationName: 'Block',
    TableName: 'Account',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'Account',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 30,
    OprationName: 'New',
    TableName: 'Account',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'حساب متحرك ',
    ControllerName: 'Account',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 31,
    OprationName: 'New',
    TableName: 'Account',
    Status: 1,
    ReferenceStatus: 'NULL',
    OprationDescription: 'حساب رئيسي ',
    ControllerName: 'Account',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'رئيسي',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 32,
    OprationName: 'Block',
    TableName: 'EntryAccounting',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'EntryAccounting',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 33,
    OprationName: 'New',
    TableName: 'EntryAccounting',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'EntryAccounting',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 34,
    OprationName: 'Block',
    TableName: 'Membership',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'Membership',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 35,
    OprationName: 'Active',
    TableName: 'Membership',
    Status: 0,
    ReferenceStatus: -1,
    OprationDescription: 'اشتراك فعال',
    ControllerName: 'Membership',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'فعال',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 36,
    OprationName: 'Block',
    TableName: 'Member',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'غير نشط \\ لا يوجد اشتركات فعالة',
    ControllerName: 'Member',
    ClassName: 'Member',
    RoleName: 'NULL',
    ArabicOprationDescription: 'غير نشط \\ لا يوجد اشتركات فعالة',
    IconClass: 'el-icon-s-release',
    Color: '#FF0202'
  },
  {
    Id: 37,
    OprationName: 'New',
    TableName: 'Member',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'نشط  ',
    ControllerName: 'Member',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 38,
    OprationName: 'Active',
    TableName: 'Member',
    Status: 1,
    ReferenceStatus: 'NULL',
    OprationDescription: 'مجمد',
    ControllerName: 'Member',
    ClassName: 'warning',
    RoleName: 'NULL',
    ArabicOprationDescription: 'مجمد',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 39,
    OprationName: 'Active',
    TableName: 'Member',
    Status: 2,
    ReferenceStatus: 'NULL',
    OprationDescription: 'يوم اضافي',
    ControllerName: 'Member',
    ClassName: 'Info',
    RoleName: 'NULL',
    ArabicOprationDescription: 'يوم اضافي',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 40,
    OprationName: 'Block',
    TableName: 'MembershipMovement',
    Status: -2,
    ReferenceStatus: 'NULL',
    OprationDescription: 'معلق',
    ControllerName: 'MembershipMovement',
    ClassName: 'Warning',
    RoleName: 'NULL',
    ArabicOprationDescription: 'معلق',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 41,
    OprationName: 'Block',
    TableName: 'MembershipMovement',
    Status: -1,
    ReferenceStatus: 'NULL',
    OprationDescription: 'منتهي',
    ControllerName: 'MembershipMovement',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'منتهي',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 42,
    OprationName: 'Not Active',
    TableName: 'MembershipMovement',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'غير مؤكد',
    ControllerName: 'MembershipMovement',
    ClassName: 'warning',
    RoleName: 'NULL',
    ArabicOprationDescription: 'غير مؤكد',
    IconClass: 'el-icon-check',
    Color: 'NULL'
  },
  {
    Id: 43,
    OprationName: 'Active',
    TableName: 'MembershipMovement',
    Status: 1,
    ReferenceStatus: 'NULL',
    OprationDescription: 'مؤكد',
    ControllerName: 'MembershipMovement',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'مؤكد',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 44,
    OprationName: 'Active',
    TableName: 'MembershipMovement',
    Status: 2,
    ReferenceStatus: 'NULL',
    OprationDescription: 'مجمد',
    ControllerName: 'MembershipMovement',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'مجمد',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 45,
    OprationName: 'Active',
    TableName: 'MembershipMovement',
    Status: 3,
    ReferenceStatus: 'NULL',
    OprationDescription: 'يوم اضافي',
    ControllerName: 'MembershipMovement',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'يوم اضافي',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 46,
    OprationName: 'Block',
    TableName: 'MembershipMovementOrder',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'MembershipMovementOrder',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 47,
    OprationName: 'Not Sure',
    TableName: 'MembershipMovementOrder',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'غير مؤكد',
    ControllerName: 'MembershipMovementOrder',
    ClassName: 'info',
    RoleName: 'NULL',
    ArabicOprationDescription: 'غير مؤكد',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 48,
    OprationName: 'Sure',
    TableName: 'MembershipMovementOrder',
    Status: 1,
    ReferenceStatus: 0,
    OprationDescription: 'مؤكد',
    ControllerName: 'MembershipMovementOrder',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'مؤكد',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 49,
    OprationName: 'Block',
    TableName: 'Cash',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'Cash',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 50,
    OprationName: 'New',
    TableName: 'Cash',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'Cash',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 51,
    OprationName: 'Block',
    TableName: 'Cheque',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'Cheque',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 52,
    OprationName: 'New',
    TableName: 'Cheque',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'Cheque',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 53,
    OprationName: 'Block',
    TableName: 'Bank',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'Bank',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 54,
    OprationName: 'New',
    TableName: 'Bank',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'Bank',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 55,
    OprationName: 'Block',
    TableName: 'Discount',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'Discount',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغى',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 56,
    OprationName: 'New',
    TableName: 'Discount',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد ',
    ControllerName: 'Discount',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-finished',
    Color: 'NULL'
  },
  {
    Id: 57,
    OprationName: 'Block',
    TableName: 'Service',
    Status: -1,
    ReferenceStatus: 0,
    OprationDescription: 'الغاء',
    ControllerName: 'Service',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'ملغي',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 58,
    OprationName: 'New',
    TableName: 'Service',
    Status: 0,
    ReferenceStatus: 'NULL',
    OprationDescription: 'جديد',
    ControllerName: 'Service',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'نشط',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 59,
    OprationName: 'Block',
    TableName: 'MembershipMovement',
    Status: -3,
    ReferenceStatus: 0,
    OprationDescription: 'ملغي',
    ControllerName: 'MembershipMovement',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'الغاء',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 60,
    OprationName: 'BlackList',
    TableName: 'Member',
    Status: -2,
    ReferenceStatus: 'NULL',
    OprationDescription: 'قائمة سوداء',
    ControllerName: 'Member',
    ClassName: 'Info',
    RoleName: 'NULL',
    ArabicOprationDescription: 'قائمة سوداء',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 61,
    OprationName: 'DoneOut',
    TableName: 'MembershipMovementOrder',
    Status: -2,
    ReferenceStatus: 0,
    OprationDescription: 'تم تعويض',
    ControllerName: 'MembershipMovementOrder',
    ClassName: 'danger',
    RoleName: 'NULL',
    ArabicOprationDescription: 'تم تعويض',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 62,
    OprationName: 'Done',
    TableName: 'MembershipMovementOrder',
    Status: -3,
    ReferenceStatus: 'NULL',
    OprationDescription: 'محسوب',
    ControllerName: 'MembershipMovementOrder',
    ClassName: 'info',
    RoleName: 'NULL',
    ArabicOprationDescription: 'تم احتساب',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  },
  {
    Id: 63,
    OprationName: 'Out',
    TableName: 'MembershipMovementOrder',
    Status: 2,
    ReferenceStatus: 0,
    OprationDescription: 'تعويض',
    ControllerName: 'MembershipMovementOrder',
    ClassName: 'success',
    RoleName: 'NULL',
    ArabicOprationDescription: 'تعويض',
    IconClass: 'el-icon-s-release',
    Color: 'NULL'
  }
]
